Repository SergeyKoval/2021_june_team4_be, pull requests merged in 2021-07, with the labels that each got.

#32 BE-006-2 (Nikolay Chornyi) Add Repositories & Service & Mapper
  src/main/java/com/exadel/discount/mapper/CategoryMapper.java
  src/main/java/com/exadel/discount/mapper/DiscountMapper.java
  src/main/java/com/exadel/discount/mapper/VendorLocationMapper.java
  src/main/java/com/exadel/discount/mapper/VendorMapper.java
  src/main/java/com/exadel/discount/repository/CategoryRepository.java
  src/main/java/com/exadel/discount/repository/DiscountRepository.java
  src/main/java/com/exadel/discount/repository/VendorLocationRepository.java
  src/main/java/com/exadel/discount/repository/VendorRepository.java
  src/main/java/com/exadel/discount/service/CategoryService.java
  src/main/java/com/exadel/discount/service/DiscountService.java
  src/main/java/com/exadel/discount/service/VendorLocationService.java
  src/main/java/com/exadel/discount/service/VendorService.java
Labels: sk

#34 BE-030 Liquibase data (Elizaveta Dubogryz)
  src/main/java/com/exadel/discount/dto/discount/CreateDiscountDTO.java
  src/main/java/com/exadel/discount/dto/discount/DiscountDTO.java
  src/main/java/com/exadel/discount/dto/location/CreateLocationDTO.java
  src/main/java/com/exadel/discount/dto/location/LocationDTO.java
  src/main/java/com/exadel/discount/dto/vendor/BaseVendorDTO.java
  src/main/java/com/exadel/discount/dto/vendor/CreateVendorDTO.java
  src/main/java/com/exadel/discount/dto/vendor/VendorDTO.java
  src/main/java/com/exadel/discount/entity/Discount.java
  src/main/java/com/exadel/discount/entity/Vendor.java
  src/main/java/com/exadel/discount/entity/VendorLocation.java
  src/main/java/com/exadel/discount/service/impl/TagServiceImpl.java
  src/main/resources/application.yaml
  src/main/resources/db/changelog/db.changelog-master.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-categories-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-cities-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-countries-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-discounts-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-discounts-locations-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-tags-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-tags-discounts-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-users-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-vendor-locations-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-add-vendors-data.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-master.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-update-discounts.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-update-vendor-locations.yaml
  src/main/resources/db/changelog/v.0.4/db.changelog-update-vendors.yaml
Labels: sk

#37 BE-006-4 (Nikolay Chornyi & Elizaveta Dubogryz) Add Service impl
  src/main/java/com/exadel/discount/entity/Category.java
  src/main/java/com/exadel/discount/exception/DeletionRestrictedException.java
  src/main/java/com/exadel/discount/exception/GlobalExceptionHandler.java
  src/main/java/com/exadel/discount/repository/CategoryRepository.java
  src/main/java/com/exadel/discount/repository/VendorLocationRepository.java
  src/main/java/com/exadel/discount/repository/VendorRepository.java
  src/main/java/com/exadel/discount/service/impl/CategoryServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/VendorLocationServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/VendorServiceImpl.java
Labels: sk

#36 BE-006-5 (Nikolay Chornyi) Add controllers (Vendor, Location, Discount, Category)
  src/main/java/com/exadel/discount/controller/CategoryController.java
  src/main/java/com/exadel/discount/controller/DiscountController.java
  src/main/java/com/exadel/discount/controller/VendorController.java
  src/main/java/com/exadel/discount/controller/VendorLocationController.java
Labels: sk

#46 Vendor locations2.0 (BE-036 geoJson Anton Rud)
  src/main/java/com/exadel/discount/entity/VendorLocation.java
  src/main/resources/db/changelog/db.changelog-master.yaml
  src/main/resources/db/changelog/v.0.5/db.changelog-master.yaml
  src/main/resources/db/changelog/v.0.5/db.changelog-rename-column-in-vendor-locations.yaml
  src/main/resources/db/changelog/v.0.5/db.changelog-update-discounts-location.yaml
Labels: sk

#28 Security + JWT (Artem & Anton & Elizabeth)
  pom.xml
  src/main/java/com/exadel/discount/controller/AuthenticationController.java
  src/main/java/com/exadel/discount/controller/TestController.java
  src/main/java/com/exadel/discount/dto/authentication/AuthenticationRequest.java
  src/main/java/com/exadel/discount/dto/authentication/AuthenticationResponse.java
  src/main/java/com/exadel/discount/dto/authentication/RefreshResponse.java
  src/main/java/com/exadel/discount/entity/Role.java
  src/main/java/com/exadel/discount/entity/User.java
  src/main/java/com/exadel/discount/entity/type/EnumPostgresSQLType.java
  src/main/java/com/exadel/discount/exception/GlobalExceptionHandler.java
  src/main/java/com/exadel/discount/exception/InvalidTokenException.java
  src/main/java/com/exadel/discount/exception/NotFoundException.java
  src/main/java/com/exadel/discount/repository/UserRepository.java
  src/main/java/com/exadel/discount/security/annotation/AdminAccess.java
  src/main/java/com/exadel/discount/security/annotation/RefreshAccess.java
  src/main/java/com/exadel/discount/security/annotation/UserAccess.java
  src/main/java/com/exadel/discount/security/config/SecurityConfig.java
  src/main/java/com/exadel/discount/security/filter/JwtFilter.java
  src/main/java/com/exadel/discount/service/JwtGenerationService.java
  src/main/java/com/exadel/discount/service/JwtService.java
  src/main/java/com/exadel/discount/service/impl/JwtServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/UserDetailsServiceImpl.java
  src/main/resources/application.yaml
Labels: sk

#50 BE-033 Add archiving for vendors (Elizaveta Dubogryz)
  src/main/java/com/exadel/discount/controller/VendorController.java
  src/main/java/com/exadel/discount/dto/discount/CreateDiscountDTO.java
  src/main/java/com/exadel/discount/dto/location/CreateLocationDTO.java
  src/main/java/com/exadel/discount/dto/location/LocationDTO.java
  src/main/java/com/exadel/discount/dto/vendor/VendorDTO.java
  src/main/java/com/exadel/discount/entity/Category.java
  src/main/java/com/exadel/discount/entity/Vendor.java
  src/main/java/com/exadel/discount/exception/DeletionRestrictedException.java
  src/main/java/com/exadel/discount/repository/VendorRepository.java
  src/main/java/com/exadel/discount/service/VendorService.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/VendorServiceImpl.java
Labels: sk

#53 The upgeaded cors policy (Artem)
  src/main/java/com/exadel/discount/security/config/SecurityConfig.java
Labels: sk

#54 BE-039 Update deleting logic (Elizaveta Dubogryz)
  lombok.config
  src/main/java/com/exadel/discount/controller/CategoryController.java
  src/main/java/com/exadel/discount/controller/VendorController.java
  src/main/java/com/exadel/discount/controller/VendorLocationController.java
  src/main/java/com/exadel/discount/dto/discount/DiscountDTO.java
  src/main/java/com/exadel/discount/exception/InvalidTokenException.java
  src/main/java/com/exadel/discount/interceptor/LoggerInterceptor.java
  src/main/java/com/exadel/discount/repository/DiscountRepository.java
  src/main/java/com/exadel/discount/repository/TagRepository.java
  src/main/java/com/exadel/discount/repository/VendorLocationRepository.java
  src/main/java/com/exadel/discount/repository/VendorRepository.java
  src/main/java/com/exadel/discount/service/VendorLocationService.java
  src/main/java/com/exadel/discount/service/impl/CategoryServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/TagServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/VendorLocationServiceImpl.java
Labels: sk

#55 BE-018-1 City country (entities, DTOs, mappers)
  src/main/java/com/exadel/discount/dto/CountryDTO.java
  src/main/java/com/exadel/discount/dto/city/BaseCityDto.java
  src/main/java/com/exadel/discount/dto/city/CityDTO.java
  src/main/java/com/exadel/discount/dto/location/CreateLocationDTO.java
  src/main/java/com/exadel/discount/dto/location/LocationDTO.java
  src/main/java/com/exadel/discount/entity/City.java
  src/main/java/com/exadel/discount/entity/Country.java
  src/main/java/com/exadel/discount/entity/VendorLocation.java
  src/main/java/com/exadel/discount/mapper/CityMapper.java
  src/main/java/com/exadel/discount/mapper/CountryMapper.java
  src/main/java/com/exadel/discount/mapper/DiscountMapper.java
  src/main/java/com/exadel/discount/mapper/VendorLocationMapper.java
  src/main/java/com/exadel/discount/mapper/VendorMapper.java
Labels: sk

#58 The Swagger has been added to the cors policy (Artem)
  src/main/java/com/exadel/discount/security/config/SecurityConfig.java
Labels: sk

#63 Docker for front access(Anton Rud)
  docker-compose.yaml
Labels: sk

#61 BE-031 Filtering, sorting and pagination for discounts (Elizaveta Dubogryz)
  pom.xml
  src/main/java/com/exadel/discount/controller/CountryController.java
  src/main/java/com/exadel/discount/controller/DiscountController.java
  src/main/java/com/exadel/discount/dto/CountryDTO.java
  src/main/java/com/exadel/discount/dto/city/BaseCityDTO.java
  src/main/java/com/exadel/discount/dto/discount/DiscountFilter.java
  src/main/java/com/exadel/discount/mapper/CityMapper.java
  src/main/java/com/exadel/discount/repository/DiscountRepository.java
  src/main/java/com/exadel/discount/repository/query/QueryPredicateBuilder.java
  src/main/java/com/exadel/discount/service/CityService.java
  src/main/java/com/exadel/discount/service/DiscountService.java
  src/main/java/com/exadel/discount/service/impl/CityServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
Labels: sk

#65 Disco update BE-045 (Anton Rud)
  src/main/java/com/exadel/discount/controller/DiscountController.java
  src/main/java/com/exadel/discount/dto/discount/CreateDiscountDTO.java
  src/main/java/com/exadel/discount/dto/discount/DiscountDTO.java
  src/main/java/com/exadel/discount/dto/discount/DiscountFilter.java
  src/main/java/com/exadel/discount/entity/Discount.java
  src/main/java/com/exadel/discount/entity/DiscountType.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
  src/main/resources/db/changelog/v.0.5/db.changelog-add-discounts-new-data.yaml
  src/main/resources/db/changelog/v.0.5/db.changelog-master.yaml
  src/main/resources/db/changelog/v.0.5/db.changelog-modify-data-type-discounts.yaml
  src/main/resources/db/changelog/v.0.5/db.changelog-rename-column-in-discounts.yaml
Labels: sk

#64 BE-044 Search for discounts (Elizaveta Dubogryz)
  src/main/java/com/exadel/discount/config/QuerydslConfig.java
  src/main/java/com/exadel/discount/controller/DiscountController.java
  src/main/java/com/exadel/discount/repository/DiscountRepository.java
  src/main/java/com/exadel/discount/repository/QueryFactoryDiscountRepository.java
  src/main/java/com/exadel/discount/repository/impl/QueryFactoryDiscountRepositoryImpl.java
  src/main/java/com/exadel/discount/service/DiscountService.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
Labels: sk

#67 Javadoc has been added for the security area (Artem)
  src/main/java/com/exadel/discount/controller/AuthenticationController.java
  src/main/java/com/exadel/discount/model/dto/authentication/AuthenticationRequest.java
  src/main/java/com/exadel/discount/model/dto/authentication/AuthenticationResponse.java
  src/main/java/com/exadel/discount/model/dto/authentication/RefreshResponse.java
  src/main/java/com/exadel/discount/security/annotation/AdminAccess.java
  src/main/java/com/exadel/discount/security/annotation/RefreshAccess.java
  src/main/java/com/exadel/discount/security/annotation/UserAccess.java
  src/main/java/com/exadel/discount/security/config/SecurityConfig.java
  src/main/java/com/exadel/discount/security/filter/JwtFilter.java
  src/main/java/com/exadel/discount/service/JwtGenerationService.java
  src/main/java/com/exadel/discount/service/JwtService.java
  src/main/java/com/exadel/discount/service/impl/JwtServiceImpl.java
Labels: documentation, sk

#60 Javadoc and an infrastructure for the exception area (Artem)
  pom.xml
  src/main/java/com/exadel/discount/controller/AuthenticationController.java
  src/main/java/com/exadel/discount/controller/GlobalExceptionHandler.java
  src/main/java/com/exadel/discount/exception/APIException.java
  src/main/java/com/exadel/discount/exception/DeletionRestrictedException.java
  src/main/java/com/exadel/discount/exception/InvalidTokenException.java
  src/main/java/com/exadel/discount/exception/NotFoundException.java
  src/main/java/com/exadel/discount/model/dto/authentication/AuthenticationRequest.java
  src/main/java/com/exadel/discount/model/exception/ExceptionCause.java
  src/main/java/com/exadel/discount/model/exception/ExceptionDetails.java
  src/main/java/com/exadel/discount/security/filter/JwtFilter.java
Labels: documentation, enhancement, sk

#70 BE-011 Hanna Kalashnik User-Coupon-Favorite model layer after restructural
  src/main/java/com/exadel/discount/model/dto/coupon/CouponDTO.java
  src/main/java/com/exadel/discount/model/dto/coupon/CreateCouponDTO.java
  src/main/java/com/exadel/discount/model/dto/favorite/CreateFavoriteDTO.java
  src/main/java/com/exadel/discount/model/dto/favorite/FavoriteDTO.java
  src/main/java/com/exadel/discount/model/dto/mapper/CouponMapper.java
  src/main/java/com/exadel/discount/model/dto/mapper/FavoriteMapper.java
  src/main/java/com/exadel/discount/model/dto/mapper/UserMapper.java
  src/main/java/com/exadel/discount/model/dto/user/UserDTO.java
  src/main/java/com/exadel/discount/model/entity/Coupon.java
  src/main/java/com/exadel/discount/model/entity/Discount.java
  src/main/java/com/exadel/discount/model/entity/Favorite.java
  src/main/java/com/exadel/discount/model/entity/User.java
Labels: sk

#74 The JwtFilter logic has been upgraded
  src/main/java/com/exadel/discount/security/filter/JwtFilter.java
Labels: sk

#73 BE-011 #2 Hanna Kalashnik: UCF Repositories
  src/main/java/com/exadel/discount/repository/CouponRepository.java
  src/main/java/com/exadel/discount/repository/FavoriteRepository.java
  src/main/java/com/exadel/discount/repository/UserRepository.java
Labels: sk

#79 BE-050 Fix sorting for discounts (Elizaveta Dubogryz)
  src/main/java/com/exadel/discount/repository/DiscountRepository.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
Labels: sk

#76 BE-011 #3 Hanna Kalashnik +filter classes for query
  src/main/java/com/exadel/discount/model/dto/coupon/CouponFilter.java
  src/main/java/com/exadel/discount/model/dto/favorite/FavoriteFilter.java
  src/main/java/com/exadel/discount/model/dto/user/UserFilter.java
Labels: sk

#80 BE-049 Update Vendor DTO (Elizaveta Dubogryz)
  src/main/java/com/exadel/discount/controller/VendorController.java
  src/main/java/com/exadel/discount/model/dto/discount/BaseDiscountDTO.java
  src/main/java/com/exadel/discount/model/dto/mapper/DiscountMapper.java
  src/main/java/com/exadel/discount/model/dto/mapper/VendorMapper.java
  src/main/java/com/exadel/discount/model/dto/vendor/VendorDTO.java
  src/main/java/com/exadel/discount/model/entity/Discount.java
  src/main/java/com/exadel/discount/repository/VendorRepository.java
  src/main/java/com/exadel/discount/service/VendorService.java
  src/main/java/com/exadel/discount/service/impl/VendorServiceImpl.java
Labels: sk

#77 BE-011 Hanna Kalashnik UCF-service layer
  src/main/java/com/exadel/discount/repository/query/SortPageUtil.java
  src/main/java/com/exadel/discount/service/CouponService.java
  src/main/java/com/exadel/discount/service/FavoriteService.java
  src/main/java/com/exadel/discount/service/UserService.java
  src/main/java/com/exadel/discount/service/impl/CouponServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/FavoriteServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/UserServiceImpl.java
Labels: sk

#85 BE-048 Add favorite to Discount DTO (Elizaveta Dubogryz)
  src/main/java/com/exadel/discount/controller/DiscountController.java
  src/main/java/com/exadel/discount/model/dto/discount/DiscountDTO.java
  src/main/java/com/exadel/discount/model/dto/mapper/FavoriteMapper.java
  src/main/java/com/exadel/discount/model/entity/Discount.java
  src/main/java/com/exadel/discount/model/entity/Favorite.java
  src/main/java/com/exadel/discount/model/entity/User.java
  src/main/java/com/exadel/discount/model/entity/VendorLocation.java
  src/main/java/com/exadel/discount/repository/DiscountRepository.java
  src/main/java/com/exadel/discount/service/DiscountService.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
Labels: sk

#75 BE-038 (Nikolay) Add update (Vendor & Category)
  src/main/java/com/exadel/discount/controller/CategoryController.java
  src/main/java/com/exadel/discount/controller/VendorController.java
  src/main/java/com/exadel/discount/model/dto/mapper/CategoryMapper.java
  src/main/java/com/exadel/discount/model/dto/mapper/VendorMapper.java
  src/main/java/com/exadel/discount/repository/CategoryRepository.java
  src/main/java/com/exadel/discount/repository/VendorRepository.java
  src/main/java/com/exadel/discount/service/CategoryService.java
  src/main/java/com/exadel/discount/service/VendorService.java
  src/main/java/com/exadel/discount/service/impl/CategoryServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/VendorServiceImpl.java
Labels: sk

#87 BE-052 Add vendorLocation filtering for discounts getAll (Elizaveta Dubogryz)
  src/main/java/com/exadel/discount/repository/DiscountRepository.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
Labels: sk

#86 BE-011 Hanna Kalashnik once coupon/fave create/del by discount Id feature
  src/main/java/com/exadel/discount/controller/CouponController.java
  src/main/java/com/exadel/discount/controller/FavoriteController.java
  src/main/java/com/exadel/discount/exception/CreationRestrictedException.java
  src/main/java/com/exadel/discount/model/dto/coupon/CreateCouponDTO.java
  src/main/java/com/exadel/discount/model/dto/favorite/CreateFavoriteDTO.java
  src/main/java/com/exadel/discount/repository/CouponRepository.java
  src/main/java/com/exadel/discount/repository/FavoriteRepository.java
  src/main/java/com/exadel/discount/service/CouponService.java
  src/main/java/com/exadel/discount/service/FavoriteService.java
  src/main/java/com/exadel/discount/service/impl/CouponServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/FavoriteServiceImpl.java
Labels: sk

#94 BE-056 (Nikolay) MockMVC test VendorLocationController
  src/test/java/com/exadel/discount/controller/VendorLocationMockIT.java
Labels: sk

#83 BE-038-1 (Nikolay) Add update (Discount)
  src/main/java/com/exadel/discount/controller/DiscountController.java
  src/main/java/com/exadel/discount/model/dto/discount/UpdateDiscountDTO.java
  src/main/java/com/exadel/discount/model/dto/mapper/DiscountMapper.java
  src/main/java/com/exadel/discount/service/DiscountService.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
Labels: sk

#98 BE-057 Change responses for Discounts search and Favorites assign/delete
  src/main/java/com/exadel/discount/controller/DiscountController.java
  src/main/java/com/exadel/discount/controller/FavoriteController.java
  src/main/java/com/exadel/discount/repository/FavoriteRepository.java
  src/main/java/com/exadel/discount/service/DiscountService.java
  src/main/java/com/exadel/discount/service/FavoriteService.java
  src/main/java/com/exadel/discount/service/impl/DiscountServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/FavoriteServiceImpl.java
Labels: sk

#97 BE-055 Statistics (Elizaveta Dubogryz)
  src/main/java/com/exadel/discount/controller/StatisticsController.java
  src/main/java/com/exadel/discount/model/dto/statistics/CategoryStatisticsDTO.java
  src/main/java/com/exadel/discount/model/dto/statistics/DiscountStatisticsDTO.java
  src/main/java/com/exadel/discount/model/dto/statistics/StatisticsFilter.java
  src/main/java/com/exadel/discount/model/dto/statistics/VendorStatisticsDTO.java
  src/main/java/com/exadel/discount/repository/CategoryRepository.java
  src/main/java/com/exadel/discount/repository/DiscountRepository.java
  src/main/java/com/exadel/discount/repository/VendorRepository.java
  src/main/java/com/exadel/discount/service/StatisticsService.java
  src/main/java/com/exadel/discount/service/impl/StatisticsServiceImpl.java
Labels: sk

#100 BE-058 Add ID to JWT token
  src/main/java/com/exadel/discount/controller/CouponController.java
  src/main/java/com/exadel/discount/controller/FavoriteController.java
  src/main/java/com/exadel/discount/security/entity/UserDetailsImpl.java
  src/main/java/com/exadel/discount/service/impl/JwtServiceImpl.java
  src/main/java/com/exadel/discount/service/impl/UserDetailsServiceImpl.java
Labels: sk

#104 BE-059 Change FavoriteDTO to DiscountDTO in favorites getAll (Elizaveta Dubogryz)
  src/main/java/com/exadel/discount/controller/FavoriteController.java
  src/main/java/com/exadel/discount/repository/CouponRepository.java
  src/main/java/com/exadel/discount/repository/DiscountRepository.java
  src/main/java/com/exadel/discount/repository/FavoriteRepository.java
  src/main/java/com/exadel/discount/repository/VendorRepository.java
  src/main/java/com/exadel/discount/service/FavoriteService.java
  src/main/java/com/exadel/discount/service/impl/FavoriteServiceImpl.java
Labels: sk

#103 BE-035 Hanna Kalashnyk DiscountTests
  pom.xml
  src/main/resources/testdata/archive_discount.sql
  src/main/resources/testdata/discount_add_test_data.sql
  src/test/java/com/exadel/discount/controller/AbstractIT.java
  src/test/java/com/exadel/discount/controller/DiscountIT.java
Labels: sk
